### PR TITLE
Add Windows workflow

### PR DESCRIPTION
**Pull request by trungleduc**
Runs tests on `ubuntu-latest` and `windows-latest`

### CODE REVIEW

**Comment by trungleduc** [comment]
The error messages look legit

```NotImplementedError: cannot instantiate 'PosixPath' on your system```

**Comment by trungleduc** [comment]
@DerThorsten please feel free to take over this PR to fix the Windows issues.

**Comment by martinRenou** [comment]
I can also have a look

**Comment by trungleduc** [comment]
> Micromamba command failed with return code 3221225477

I got the same error code while testing `jupyterlite_xeus` on my Windows PC

**Pull request closed without merging**
