### PR TITLE
merge-able configs, per-package packaging, misc

### PR DESCRIPTION
**Pull request by DerThorsten**
* added capabilities to have multiple empack configurations which are merged in. Note that the additional config files have a slightly different schema since we cannot force them to contain the `default` key. Otherwise they would always overwrite the "base-configs" default.
This can be invoked by passing multiple `--config` arguments
```
 empack pack env \
    --env-prefix $MAMBA_ROOT_PREFIX/envs/env1 \
    --outname env_2 \
    --config $GITHUB_WORKSPACE/tests/empack_test_config.yaml \
    --config $GITHUB_WORKSPACE/tests/empack_test_extra_config.yaml
```
* Added option to pack conda environment st. it creates a `*.data`/`*.js` for each package individually (via `--split` in empack cli):

 A <some_name>.js file, like the one below, is generated by the file packager to trigger all the individual imports:
```JavaScript
export default async function(){
    let promises = [];
    promises.push(import('./python-3.10.2-h_hash_6_cpython.js'));
    promises.push(import('./dataclasses-0.8-pyhc8e2a94_3.js'));
    promises.push(import('./numpy-1.21.4-py310h672cd09_0.js'));
    promises.push(import('./pyb2d-0.7.2-py310h57b18ff_0.js'));
    promises.push(import('./wheel-0.37.1-pyhd8ed1ab_0.js'));
    promises.push(import('./pydantic-0.18.2-py_0.js'));
    promises.push(import('./pyparsing-3.0.9-pyhd8ed1ab_0.js'));
    await Promise.all(promises);
}
```
Note that this should be way better for caching!  instead of caching one big `python_data.data` which can be outdated/ / wrongly cached, we now cache `numpy-1.21.4-py310h672cd09_0.data` . This cannot be outdated/wrongly cached since this would change the hash

In the user-code one now has to do smth like (where <some_name> is `python_data` in this example

``` JavaScript
const { default: load_all }  = await import('./python_data.js')
await load_all()    
```

* Added code to manipulate the emscripten generated JavaScript files to allow for better logging / a better progress bar
* Added `empack --version`  to `CLI`
* Added a better function for error handling in the `CLI`

### CODE REVIEW

**Comment by wolfv** [comment]
> This cannot be outdated/wrongly cached since this would change the hash

this is only true if we always change the build number. I would suggest appending a timestamp or sha256 sum as a query string, e.g. `blabla.data?sha256=123123123` (that's often used for "cache busting").

**Comment by DerThorsten** [comment]
> > This cannot be outdated/wrongly cached since this would change the hash
> 
> this is only true if we always change the build number. I would suggest appending a timestamp or sha256 sum as a query string, e.g. `blabla.data?sha256=123123123` (that's often used for "cache busting").

Can't we assume that we change the build number? In fact, we prevent uploading already existing packages in emscripten-forge, so I thought this should be fine.

**Comment by wolfv** [comment]
Hmm, I am pretty sure we upload (right now) with `--force` which doesn't prevent that. I would not assume it. Also annoying for local development (where you produce the same build number often). 
What's so hard to calculate the SHA256 and stick it at the end?

**Comment by DerThorsten** [comment]
I think we remove the force since we got problems from it
https://github.com/emscripten-forge/recipes/blob/dbae449eb5b210b6449eb0cbc69619108f7a3e99/.github/workflows/build_recipes.yaml#L186

**Comment by DerThorsten** [comment]
@wolfv  jeah we can add the SHA256
...btw I always assumed the hash in the filename is smth like SHA256 of the content^^

**Comment by DerThorsten** [comment]
the only annoying part: the part where we would to ` blabla.data?sha256=123123123`  is generated by emscipten...

**Comment by DerThorsten** [comment]
@wolfv I would rather merge this as is and add the SHA256 in an another PR

**Pull request merged**
