### PR TITLE
Change list-of-POSIX-paths to list-of-strings in yield of `iterate_pip_pkg_record()` function

### PR DESCRIPTION
**Pull request by michaelweinold**
This hopefully solves:

- https://github.com/jupyterlite/xeus/issues/113

### CODE REVIEW

**Review by DerThorsten — APPROVED** [review]

**Comment by DerThorsten** [comment]
lgtm, the failing test seems unrelated

**Comment by michaelweinold** [comment]
Once this is merged and a bugfix-release published - is it sufficient to specify the version in the `build-environment.yml`?

I am a little confused because `empack` is being installed in the mamba environment where the packages from `environment.yml` are all added.

**Comment by michaelweinold** [comment]
@DerThorsten, is there any way a bugfix release could be made before mid-September. We were hoping to switch from Pyodide to the more performant XEUS kernel - but this is currently blocking us 🙈

**Comment by DerThorsten** [comment]
@michaelweinold Sure, for releases, I usually summon @martinRenou :)

**Comment by martinRenou** [comment]
The test failure boils down to this:

```
Traceback (most recent call last):  File "main.py", line 6, in <module>
    from scipy.linalg import lapack
  File "/lib/python3.11/site-packages/scipy/linalg/__init__.py", line 206, in <module>
    from ._misc import *
  File "/lib/python3.11/site-packages/scipy/linalg/_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/lib/python3.11/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
AttributeError: _ARRAY_API not found
error while evaluating main file: {has_err: true, message: ImportError: numpy.core.multiarray failed to impor…ap>(1181): _find_and_load
  main.py(6): <module>
, error: ImportError: numpy.core.multiarray failed to impor…ap>(1181): _find_and_load
  main.py(6): <module>
}
```

Did we upload a new version of scipy/numpy recently?

**Comment by martinRenou** [comment]
Definitely unrelated to this PR though

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
I had to revert this PR as it seems it's breaking pip packages: https://github.com/emscripten-forge/empack/issues/105

Will release a patch release right away

**Pull request merged**
